name: Quality Assurance

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Go
        uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Install revive
        run: go install github.com/mgechev/revive@latest

      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: v2.12.1
          args: ./...

      - name: Run revive
        run: revive -config ./revive.toml ./...

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Go
        uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: go test ./...
